# This workflow checks that any added benchmarks *run* on the latest Matplotlib
# release. It does _not_ update any results.
name: Benchmark Check
on: [push, pull_request]

jobs:
  asv:
    name: asv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install asv
        run: pip3 install asv matplotlib

      - name: Run asv
        run: |
          asv machine --yes
          asv dev
